#后台启动命令：nohup java -jar holyw-0.0.1-SNAPSHOT.jar
server:
  port: 443
  servlet:
    context-path: /holyw
  ssl:
    key-store: holyw.com.jks
    key-store-password: jiang1227
    key-store-type: JKS
    #key-alias: 1
    keyAlias: holyw.com
spring:
  datasource:
    url: jdbc:mysql://holyw.com:3306/holyw
    username: root
    password: jiang1227
    driver-class-name: com.mysql.jdbc.Driver
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
tomcat:
  uri-encoding: UTF-8