#后台启动命令：nohup java -jar holyw-0.0.1-SNAPSHOT.jar
server:
  port: 80
  servlet:
    context-path: /holyw
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/holyw
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
tomcat:
  uri-encoding: UTF-8